---
title: "Final Project"
author: "Annika Engstrom"
date: "10/19/2018"
output: html_document
---

```{r setup, include=FALSE, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(dplyr)
library(readxl)
library(ggplot2)
library(foreign)
library(shiny)
library(rsconnect)
library(readr)
library(forcats)
```

```{r message = FALSE, cache = TRUE}

download.file("http://gss.norc.org/documents/spss/GSS_spss.zip", "GSS_spss.zip", quiet = TRUE)

unzip("GSS_spss.zip")

gss <- read.spss("GSS7216_R4.sav", to.data.frame = TRUE)

#For this project, I only wanted to look at views towards gay rights since the year 2003, as this was the year in which sexual relations between same-sex couples was deemed legal by the Supreme Court. This is widely cited as a turning point in the history of gay rights in the United States, and is very likely to mark a turning point in people's open views on gay rights when responding to surveys such as the General Social Survey. 
gss1 <- gss %>%
  filter(YEAR >= 2003) %>%
  select(ID, YEAR, AGE, MARITAL, SEX, INCOME, MARHOMO, SPKHOMO, COLHOMO, LIBHOMO, RELIG, PARTYID) %>%
  filter(!is.na(MARHOMO)) %>%
  filter(!is.na(SPKHOMO)) %>%
  filter(!is.na(COLHOMO)) %>%
  filter(!is.na(LIBHOMO)) %>%
  filter(!is.na(SEX)) %>%
  filter(!is.na(MARITAL)) %>%
  filter(!is.na(INCOME)) %>%
  filter(!is.na(AGE)) %>%
  arrange(ID)

gss1$AGE = as.numeric(as.character(gss1$AGE))

gss1 <- gss1 %>%
  mutate(AGE = case_when(
    AGE %in% c(18:24) ~ "18-24",
    AGE %in% c(25:34) ~ "25-34",
    AGE %in% c(35:44) ~ "35-44",
    AGE %in% c(45:54) ~ "45-54",
    AGE %in% c(55:64) ~ "55-64",
    AGE %in% c(65:120) ~ "65+")) %>%
  group_by(AGE)

gss1$INCOME <- fct_collapse(gss1$INCOME, 
                     `<1000` = c("LT $1000"), 
                     `1000-3999` = c("$1000 TO 2999", "$3000 TO 3999"), 
                     `4000-5999` = c("$4000 TO 4999", "$5000 TO 5999"), 
                     `6000-7999` = c("$6000 TO 6999", "$7000 TO 7999"), 
                     `8000-9999` = c("$8000 TO 9999"), 
                     `10000-14999` = c("$10000 - 14999"), 
                     `15000-19999` = c("$15000 - 19999"), 
                     `20000-24999` = c("$20000 - 24999"), 
                     `>25000` = c("$25000 OR MORE"))

gss1$MARHOMO <- fct_collapse(gss1$MARHOMO, 
                     `1` = c("STRONGLY AGREE"), 
                     `0.5` = c("AGREE"), 
                     `0` = c("NEITHER AGREE NOR DISAGREE"), 
                     `-0.5` = c("DISAGREE"), 
                     `-1` = c("STRONGLY DISAGREE"))

gss1$MARHOMO = as.numeric(as.character(gss1$MARHOMO))

gss1$SPKHOMO <- fct_collapse(gss1$SPKHOMO, 
                     `1` = c("ALLOWED"), 
                     `-1` = c("NOT ALLOWED"))

gss1$SPKHOMO = as.numeric(as.character(gss1$SPKHOMO))

gss1$COLHOMO <- fct_collapse(gss1$COLHOMO, 
                     `1` = c("ALLOWED"), 
                     `-1` = c("NOT ALLOWED"))

gss1$COLHOMO = as.numeric(as.character(gss1$COLHOMO))

gss1$LIBHOMO <- fct_collapse(gss1$LIBHOMO, 
                     `1` = c("NOT REMOVE"), 
                     `-1` = c("REMOVE"))

gss1$LIBHOMO = as.numeric(as.character(gss1$LIBHOMO))

gss1 <- gss1 %>%
  group_by(AGE, INCOME, MARITAL, YEAR, SEX, PARTYID) %>%
  summarise(MARHOMO = mean(MARHOMO), SPKHOMO = mean(SPKHOMO), COLHOMO = mean(COLHOMO), LIBHOMO = mean(LIBHOMO))

write_rds(gss1, "data1.rds")

runApp("shiny.r")   

 
```